In [26]:
import seaborn as sns
import matplotlib.pyplot as plt

# Ekhon apni dataset load ba graph toiri korte parben
# jemon:
# sns.load_dataset('iris')

In [27]:
import pandas as pd
import numpy as np
import seaborn as sns
import requests
from io import StringIO

  
  ১. Requests (External Library)
             requests holo Python-er ekti khub-i popular Third-party Library। Eta Python-er sathe built-in thake na, tai amader pip install requests diye eta alada bhabe install korte hoy.
  StringIO : Eta text data-ke ekti "File"-er moto treat kore.

In [28]:
df=pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

১. Data Download kora
requests.get(url1) line-ti diye GitHub-er oi URL theke CSV file-er raw data-ti sangrah kora hochhe.

In [29]:
url1 = ("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")
url1

'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'

২. Text ke File-er moto kora
StringIO(data1.text) ekhane khub guruttopurno. Python-e pd.read_csv() sadharonoto computer-e thaka kono file-er path khoje. Kintu jokhon data net theke text hishebe ashe, tokhon StringIO sheti ke ekti "virtual file"-e rupantor kore jate Pandas bhabte pare eta ekti real file.

In [30]:
data1 = requests.get(url1)

৩. DataFrame-e rupantor
df5 = pd.read_csv(df4) line-ti oi virtual file theke data niye ekti Table ba DataFrame (df5) toiri korche.

In [31]:
df4 = StringIO(data1.text)

In [32]:
df5 = pd.read_csv(df4)
df5[10:15]

    sepal.length  sepal.width  petal.length  petal.width variety
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa